2018-04-03 16:36:04,418 ERROR [ERROR]: Caught exception in the launcher.
2018-04-03 16:36:04,440 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-03 16:36:04,440 ERROR [ERROR]: Exception: 
END_PHASE_EXECUTE_MOVE
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 184, in run
    self.step(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 132, in step
    EVENT_BUS.invoke_handlers(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\event\eventbus.py", line 46, in invoke_handlers
    handler(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 94, in handle_menu_selections
    self.set_screen_from_mode(Mode.BATTLE, event.mapname)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 57, in set_screen_from_mode
    Managers.initialize_managers(map_name, bitmap, pieces, teams, upgrades, meta)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 74, in initialize_managers
    Managers.turn_manager = TurnManager(meta)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\turnmanager.py", line 16, in __init__
    super().__init__()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\engine\gameobject.py", line 10, in __init__
    self.register_handlers(EVENT_BUS)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\turnmanager.py", line 36, in register_handlers
    event_bus.register_handler(EventType.END_PHASE_EXECUTE_MOVE, self.progress_phase)

  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 324, in __getattr__
    raise AttributeError(name) from None

2018-04-03 16:43:57,467 ERROR [ERROR]: Caught exception in the launcher.
2018-04-03 16:43:57,468 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-03 16:43:57,468 ERROR [ERROR]: Exception: 
<Setting.ANIMATION_SPEED: 'ANIMATION_SPEED'>
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\mainmenu.py", line 296, in render
    display_string = get_string(formatted_strings, option[0]).format(SETTINGS.get_unsaved(option[0]))

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\settings.py", line 94, in get_unsaved
    return self.unsaved_settings[setting]

2018-04-03 16:44:39,611 ERROR [ERROR]: Caught exception in the launcher.
2018-04-03 16:44:39,616 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-03 16:44:39,616 ERROR [ERROR]: Exception: 
<Setting.ANIMATION_SPEED: 'ANIMATION_SPEED'>
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 184, in run
    self.step(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 129, in step
    INPUT_CONTROLLER.invoke_handlers(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\control\inputcontroller.py", line 55, in invoke_handlers
    handler()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\mainmenu.py", line 236, in raise_setting
    SETTINGS.raise_setting(selection)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\settings.py", line 102, in raise_setting
    self.set_setting(setting, self.unsaved_settings[setting] + setting_interval[setting])

2018-04-03 16:57:49,689 ERROR [ERROR]: Caught exception in the launcher.
2018-04-03 16:57:49,694 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-03 16:57:49,694 ERROR [ERROR]: Exception: 
<Team.BLUE: '[BLU]'>
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 209, in render
    Managers.player_manager.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\playermanager.py", line 81, in render
    cursor.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\cursor.py", line 238, in render
    game_screen.blit(spr_wait_icon[self.team], (self.gx * GRID_WIDTH, self.gy * GRID_HEIGHT))

2018-04-03 20:07:00,964 ERROR [ERROR]: Caught exception in the launcher.
2018-04-03 20:07:00,972 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-03 20:07:00,972 ERROR [ERROR]: Exception: 
line() takes no keyword arguments
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 205, in render
    Managers.piece_manager.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\piecemanager.py", line 374, in render
    piece.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\piece\piece.py", line 717, in render
    (self.current_order.tx * GRID_WIDTH, self.current_order.ty * GRID_HEIGHT), width=2)

2018-04-03 20:07:34,402 ERROR [ERROR]: Caught exception in the launcher.
2018-04-03 20:07:34,404 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-03 20:07:34,404 ERROR [ERROR]: Exception: 
invalid color argument
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 205, in render
    Managers.piece_manager.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\piecemanager.py", line 374, in render
    piece.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\piece\piece.py", line 717, in render
    (self.current_order.tx * GRID_WIDTH, self.current_order.ty * GRID_HEIGHT), 2)

2018-04-03 20:08:32,373 ERROR [ERROR]: Caught exception in the launcher.
2018-04-03 20:08:32,374 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-03 20:08:32,374 ERROR [ERROR]: Exception: 
can only concatenate tuple (not "int") to tuple
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 205, in render
    Managers.piece_manager.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\piecemanager.py", line 374, in render
    piece.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\piece\piece.py", line 716, in render
    pygame.draw.line(game_screen, light_team_color[self.team], (self.gx * GRID_WIDTH + 12, self.gy * GRID_HEIGHT) + 12,

2018-04-04 13:07:34,723 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 13:07:34,728 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 13:07:34,728 ERROR [ERROR]: Exception: 
'PIECE_COUNT'
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\mainmenu.py", line 333, in render
    self.render_map_preview(game_screen, option[0])

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\mainmenu.py", line 274, in render_map_preview
    screen.blit(draw_text(formatted_strings["PIECE_COUNT"].format(piece_count), light_color, shadow_color[Team.RED]),

2018-04-04 13:21:20,630 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 13:21:20,631 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 13:21:20,631 ERROR [ERROR]: Exception: 
subsurface rectangle outside surface area
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\mainmenu.py", line 346, in render
    self.render_map_preview(game_screen, option[0])

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\mainmenu.py", line 278, in render_map_preview
    minimap = generate_minimap(bitmap).subsurface(0, 0, container_width - 24, container_height - 24)

2018-04-04 14:46:55,442 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 14:46:55,458 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 14:46:55,459 ERROR [ERROR]: Exception: 
<UpgradeType.RESOURCE_PRODUCTION_1: 1>
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 212, in render
    Managers.player_manager.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\playermanager.py", line 81, in render
    cursor.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\cursor.py", line 241, in render
    self.menu.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\menupopup.py", line 184, in render
    self.detailbox.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\detailbox.py", line 121, in render
    y_offset = self.render_upgrade_attributes(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\detailbox.py", line 85, in render_upgrade_attributes
    ui_screen.blit(spr_pieces[self.team][self.target].subsurface(0, 0, 24, 24), (self.x + 2, self.y + 8 + y_offset))

2018-04-04 15:41:39,839 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 15:41:39,841 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 15:41:39,842 ERROR [ERROR]: Exception: 
<UpgradeAttribute.NEW_STAT: 1>
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\main.py", line 187, in run
    self.render()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\managers\managers.py", line 212, in render
    Managers.player_manager.render(map_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\managers\playermanager.py", line 81, in render
    cursor.render(game_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\cursor.py", line 241, in render
    self.menu.render(game_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\menupopup.py", line 184, in render
    self.detailbox.render(game_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\detailbox.py", line 147, in render
    y_offset = self.render_upgrade_attributes(ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\detailbox.py", line 109, in render_upgrade_attributes
    for piece_type, attributes in upgrade[UpgradeAttribute.NEW_STAT].items():

2018-04-04 15:54:00,590 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 15:54:00,591 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 15:54:00,591 ERROR [ERROR]: Exception: 
'PieceArchetype' object is not iterable
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 212, in render
    Managers.player_manager.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\playermanager.py", line 81, in render
    cursor.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\cursor.py", line 241, in render
    self.menu.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\menupopup.py", line 184, in render
    self.detailbox.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\detailbox.py", line 162, in render
    y_offset = self.render_upgrade_attributes(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\detailbox.py", line 115, in render_upgrade_attributes
    for enemy_type, value in multipliers:

2018-04-04 15:55:25,016 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 15:55:25,018 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 15:55:25,019 ERROR [ERROR]: Exception: 
<PieceArchetype.WORKER: 1>
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\main.py", line 187, in run
    self.render()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\managers\managers.py", line 212, in render
    Managers.player_manager.render(map_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\managers\playermanager.py", line 81, in render
    cursor.render(game_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\cursor.py", line 241, in render
    self.menu.render(game_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\menupopup.py", line 184, in render
    self.detailbox.render(game_screen, ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\detailbox.py", line 162, in render
    y_offset = self.render_upgrade_attributes(ui_screen)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\ui\detailbox.py", line 123, in render_upgrade_attributes
    ui_screen.blit(spr_pieces[self.team][enemy_type].subsurface(0, 0, 24, 24), (self.x + 2 + 48, self.y + 8 + y_offset))

2018-04-04 16:05:03,413 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 16:05:03,415 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 16:05:03,415 ERROR [ERROR]: Exception: 
<UpgradeAttribute.NEW_ATTACK_MULTIPLIER: 3>
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 187, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 148, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battle.py", line 40, in render
    Managers.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\managers.py", line 212, in render
    Managers.player_manager.render(map_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\playermanager.py", line 81, in render
    cursor.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\cursor.py", line 241, in render
    self.menu.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\menupopup.py", line 184, in render
    self.detailbox.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\detailbox.py", line 185, in render
    y_offset = self.render_upgrade_attributes(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\ui\detailbox.py", line 145, in render_upgrade_attributes
    for piece_type, new_pieces in upgrade[UpgradeAttribute.NEW_ATTACK_MULTIPLIER].items():

2018-04-04 16:11:04,927 ERROR [ERROR]: Caught exception in the launcher.
2018-04-04 16:11:04,932 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-04 16:11:04,932 ERROR [ERROR]: Exception: 
'set' object has no attribute 'set_palette'
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 162, in run
    load_assets()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\resources\assets.py", line 332, in load_assets
    spr_combat_icon[team] = swap_palette(spr_combat_icon[Team.RED], unit_palette[team])

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\util\drawingutil.py", line 16, in swap_palette
    new_sprite.set_palette(palette)

